spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ticketera_db
    username: user_ticketera
    password: pass_ticketera
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true