spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${TICKETERA_DB_URL}
    username: ${TICKETERA_DB_USERNAME}
    password: ${TICKETERA_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false